### ISSUE TITLE
Error if you select "all open tasks"

### ISSUE THREAD

**Issue by mokraemer** [mantisbt-plugins/Tasks#1]
`#1146: Table 'aldente-it_qa.plugin_Tasks_definede' doesn't exist für die Abfrage: SELECT a.*,b.taskcat_title FROM plugin_Tasks_definede as a,plugin_Tasks_cat as b WHERE a.taskcat_id=b.taskcat_id and task_completed = '0000-00-00 00:00:00' and task_handler>0 ORDER BY task_handler,task_due ASC.`

**Comment by mokraemer** [comment]
looks like this is wrong:
`plugins/Tasks/pages/all_tasks.php:$query = "SELECT a.*,b.taskcat_title FROM {plugin_Tasks_defined}e as a,{plugin_Tasks_cat} as b  WHERE a.taskcat_id=b.taskcat_id and task_completed = '0000-00-00 00:00:00' and task_handler>0 ORDER BY task_handler,task_due ASC";`

must be
`plugins/Tasks/pages/all_tasks.php:$query = "SELECT a.*,b.taskcat_title FROM {plugin_Tasks_defined} as a,{plugin_Tasks_cat} as b  WHERE a.taskcat_id=b.taskcat_id and task_completed = '0000-00-00 00:00:00' and task_handler>0 ORDER BY task_handler,task_due ASC";`

**Comment by ghost** [comment]
Fixed 2 files which had the same typo
