### ISSUE TITLE
Error assigning Bug

### ISSUE THREAD

**Issue by mokraemer** [mantisbt-plugins/Tasks#10]
`#1103: Incorrect table name 'plugin_Tasks_autodefinedplugin_Tasks_autodefinedplugin_Tasks_autodefined' für die Abfrage: select * from plugin_Tasks_autodefinedplugin_Tasks_autodefinedplugin_Tasks_autodefined where project_id=1 and category_id=0 and autotask_status = 50`

**Comment by mokraemer** [comment]
`Tasks.php:				$query		="select * from {plugin_Tasks_autodefined}{plugin_Tasks_autodefined}{plugin_Tasks_autodefined} where project_id=$project and category_id=0 and autotask_status = $status";`

**Comment by ghost** [comment]
Corrected this wrong query
