### ISSUE TITLE
Positions should be set in config / some do not work

### ISSUE THREAD

**Issue by mokraemer** [mantisbt-plugins/Tasks#11]
setting
`event_declare('EVENT_VIEW_BUG_DETAILS2');`
has no effect
setting
`event_declare('EVENT_VIEW_BUG_DETAILS');`
results in a broken page.

**Comment by ghost** [comment]
Both will work, I have corrected the readme so the correct entry is stated there for 'EVENT_VIEW_BUG_DETAILS2'
