### ISSUE TITLE
Date/Time is not correct

### ISSUE THREAD

**Issue by mokraemer** [mantisbt-plugins/Tasks#13]
Output of some date fields show
"Y.m.d" or "d.m.Y" and not what was set in the settings.

**Comment by mokraemer** [comment]
`$t_date_format = config_get( 'normal_date_format' );`

**Comment by mokraemer** [comment]
I try to give you a pull request - depends if I manage to use git. I've never (really) used git.

**Comment by ghost** [comment]
This has been adjusted in version 3.30
