### ISSUE TITLE
Error on adding a task

### ISSUE THREAD

**Issue by mokraemer** [mantisbt-plugins/Tasks#2]
`#1366: Incorrect integer value: '' for column `aldente-it_qa`.`plugin_Tasks_defined`.`taskcat_id` at row 1 für die Abfrage: INSERT INTO plugin_Tasks_defined ( bug_id,task_user, task_handler,task_title,task_desc,task_created,task_due,task_changed,taskcat_id,task_group )
VALUES ( '2648','1', '1', 'test', 'xx', NOW(), '2023-09-29 14:05', NOW(), '','0').
`

**Comment by mokraemer** [comment]
```
pages/task_action_add.php:
$taskcat        = (int)$_REQUEST['cat_id'];
```

**Comment by ghost** [comment]
This has been adjusted in version 3.30
