### ISSUE TITLE
documentation Automated tasks

### ISSUE THREAD

**Issue by mokraemer** [mantisbt-plugins/Tasks#5]
it is not clear how this works.

Are these tasks added everytime an issue hits a special state?

**Comment by ghost** [comment]
That indeed is the idea. if a issue hits a certain status, the plugin will add the predefined tasks to the handler defined.
This is also stated in the readme:
_One can also setup auto tasks per project/category.
This means that whenever an issue is reported with the defined project/category,
the system automatically will assign various tasks to predefined users.
The due date will be the date of reporting plus a defined number of working days._
