### ISSUE TITLE
missing htaccess file

### ISSUE THREAD

**Issue by mokraemer** [mantisbt-plugins/Tasks#6]
file ./plugins/.htaccess does not allow loading ressources from e.g. Tasks/pages/css

**Comment by ghost** [comment]
There is no CSS directory with the tasks plugin and a htaccess file is not needed either

**Comment by mokraemer** [comment]
but a js and an image dir - both need a .htaccess file to allow getting the ressources.

**Comment by mokraemer** [comment]
AH01630: client denied by server configuration: .../plugins/Tasks/pages/js, referer: https://xxx/plugins/Tasks/pages/task_action_add.php

**Comment by mokraemer** [comment]
argh this is the same as the datepicker:
`"GET /plugins/Tasks/pages/js/list-1.5.0.min.js HTTP/2.0" 403 479 "https://xxx/plugins/Tasks/pages/task_action_add.php"`

**Comment by ghost** [comment]
Which version of the plugin are you using?  The  plugin does not have its own  "list-1.5.0.min.js" .
.htaccess files are not required either.
