### ISSUE TITLE
css files missing

### ISSUE THREAD

**Issue by mokraemer** [mantisbt-plugins/Tasks#7]
e.g.
/plugins/Tasks/pages/css/bootstrap-datetimepicker-4.17.47.min.css

**Comment by ghost** [comment]
This I do not recognize, which version are you running?

**Comment by mokraemer** [comment]
it is in the serverlogs. I've downloaded the plugin on this page via code download.
mantis 2.25.7

I gues this comes from mantis itself:
```
"GET /css/bootstrap-datetimepicker-4.17.47.min.css HTTP/2.0" 200 ... https://xxx/view_all_bug_page.php?refresh=true
"GET /plugins/Tasks/pages/js/bootstrap-datetimepicker-4.17.47.min.js HTTP/2.0" 403 ... https://xxx/plugins/Tasks/pages/task_action_add.php

```
but it is also requested on task pages as you have a datepicker here. Just replace it via traditinal datetime_local input field.

**Comment by ghost** [comment]
Same comment as for the htaccess issue. Not sure what tour setup is but this I cannot reproduce.
