### ISSUE TITLE
update tasks does not work

### ISSUE THREAD

**Issue by mokraemer** [mantisbt-plugins/Tasks#8]
the following error is emmited:
`Refused to execute inline event handler because it violates the following Content Security Policy directive: "script-src 'nonce-OHTtiXJTv-opLeRC' 'nonce-NGRhMzc0Nzg2ODQ3' 'self'". Either the 'unsafe-inline' keyword, a hash ('sha256-...'), or a nonce ('nonce-...') is required to enable inline execution. Note that hashes do not apply to event handlers, style attributes and javascript: navigations unless the 'unsafe-hashes' keyword is present.`

**Comment by mokraemer** [comment]
I suggest to replace '<a href="#" '
e.g. a button, or at least remove href="#", because it makes the page go to the top, which is confusing.

A nonce must be added to the script calls. Looking at the implementation of
[Lightbox](https://github.com/mantisbt-plugins/Lightbox/blob/master/Lightbox.php)
It is simple:
set csp header (setting the nonce: crypto_generate_uri_safe_nonce) via EVENT_CORE_HEADERS
and adding the nonce to the script calls

**Comment by mokraemer** [comment]
it is working, if you set
`http_csp_add( 'default-src', 'unsafe-inline' );`
in csp_headers

but this is just a workaround, no safe code.

**Comment by mokraemer** [comment]
I don't see how to access that token from e.g. Tasks/pages/tasks_form.php - but I did not read the plugin guide. But with csp enabled, it does not work atm.

**Comment by dregad** [comment]
Don't disable CSP.

Best way to fix this is to not use any in-line scripts and move them to a js file which you include on pages where it's needed, via EVENT_LAYOUT_RESOURCES hook.

**Comment by mokraemer** [comment]
got it working - this is the whole patch-set for the bugs I fixed:
[changes.txt](https://github.com/mantisbt-plugins/Tasks/files/12704275/changes.txt)

**Comment by ghost** [comment]
Thanks for this, I will review and release a new version once all is done.

**Comment by mokraemer** [comment]
Thanks for your work on this plugin.
I am still in evaluating phase - I hope to improve our internal workflow and hope this plugin helps me with this. If it does, maybe I can contribute some more.

**Comment by ghost** [comment]
Absolutely, you are welcome, will add you to the credits too.

**Comment by ghost** [comment]
Perhaps we can communicate directly so we can bring this plugin to a higher level. My email address can be found in the tasks.php
